### ISSUE TITLE
Loss error

### ISSUE THREAD

**Issue by trikim** [luxiaolili/IDM-VTON-train#1]
Thanks for sharing the training code of IDM-VTON.
Around after 2000 steps training, There‘s a problem of 'nan' by using bitsandbytes.optim.AdamW8bit. But if don't use bitsandbytes.optim.AdamW8bit, the GPUs are out of memory.

Another question is that the paper saids they use adam with batch_size=6, width=768, height=1024, do you know how they succeed to train and GPU is not out of memory?

**Comment by luxiaolili** [comment]
> Thanks for sharing the training code of IDM-VTON. Around after 2000 steps training, There‘s a problem of 'nan' by using bitsandbytes.optim.AdamW8bit. But if don't use bitsandbytes.optim.AdamW8bit, the GPUs are out of memory.
> 
> Another question is that the paper saids they use adam with batch_size=6, width=768, height=1024, do you know how they succeed to train and GPU is not out of memory?

![default](https://github.com/luxiaolili/IDM-VTON-train/assets/174935326/f0d4438d-d234-4f52-8bf3-43ba1b7c8e3b)
I try to train it use adamw8bit, It is OK, not find the loss is NaN. I train it on  1 A800 GPU, at least 50G for training. Maybe the author use more gpus.

**Comment by luxiaolili** [comment]
You can check the data is ok or the config is ok , I generate the image_mask and agnostic by get_mask.py
## get the cloth mask and agnostic-v3.3 
python get_mask.py ../zalando-hd-resized/train/image  image_mask agnostic-v3.3
### Chang the config
stable-diffusion-xl-1.0-inpainting-0.1 unet config update "encoder_hid_dim_type":"ip_image_proj", "encoder_hid_dim":1280
stabilityai/stable-diffusion-xl-base-1.0 unet config  delete "addition_embed_type":"text_time"
Hope you success

**Comment by trikim** [comment]
> > Thanks for sharing the training code of IDM-VTON. Around after 2000 steps training, There‘s a problem of 'nan' by using bitsandbytes.optim.AdamW8bit. But if don't use bitsandbytes.optim.AdamW8bit, the GPUs are out of memory.
> > Another question is that the paper saids they use adam with batch_size=6, width=768, height=1024, do you know how they succeed to train and GPU is not out of memory?
> 
> ![default](https://private-user-images.githubusercontent.com/174935326/347848117-f0d4438d-d234-4f52-8bf3-43ba1b7c8e3b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTYyMjcsIm5iZiI6MTcyMDc1NTkyNywicGF0aCI6Ii8xNzQ5MzUzMjYvMzQ3ODQ4MTE3LWYwZDQ0MzhkLWQyMzQtNGY1Mi04YmYzLTQzYmExYjdjOGUzYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMDM0NTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTVkN2JlOTAyYjA1ZmJlZWVkYjQ5ODk1YzdmODJhZDA4NDU5ZGJjMjMzNTBlMTU5OWQwMDQ4ODZlMWVkMDViOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s_4SpMhcItO24BszoSW-D1Iozp-4_hThK6eUsMBf9-8) I try to train it use adamw8bit, It is OK, not find the loss is NaN. I train it on 1 A800 GPU, at least 50G for training. Maybe the author use more gpus.

I train it with 8 A800, the loss is ok in the log, but after a specific step, the model generate whole black image. if I use torch.autograd.set_detect_anomaly(True) in the “for loop” training，I can detect the nan error.

**Comment by luxiaolili** [comment]
> > > Thanks for sharing the training code of IDM-VTON. Around after 2000 steps training, There‘s a problem of 'nan' by using bitsandbytes.optim.AdamW8bit. But if don't use bitsandbytes.optim.AdamW8bit, the GPUs are out of memory.
> > > Another question is that the paper saids they use adam with batch_size=6, width=768, height=1024, do you know how they succeed to train and GPU is not out of memory?
> > 
> > 
> > ![default](https://private-user-images.githubusercontent.com/174935326/347848117-f0d4438d-d234-4f52-8bf3-43ba1b7c8e3b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTYyMjcsIm5iZiI6MTcyMDc1NTkyNywicGF0aCI6Ii8xNzQ5MzUzMjYvMzQ3ODQ4MTE3LWYwZDQ0MzhkLWQyMzQtNGY1Mi04YmYzLTQzYmExYjdjOGUzYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMDM0NTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTVkN2JlOTAyYjA1ZmJlZWVkYjQ5ODk1YzdmODJhZDA4NDU5ZGJjMjMzNTBlMTU5OWQwMDQ4ODZlMWVkMDViOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s_4SpMhcItO24BszoSW-D1Iozp-4_hThK6eUsMBf9-8) I try to train it use adamw8bit, It is OK, not find the loss is NaN. I train it on 1 A800 GPU, at least 50G for training. Maybe the author use more gpus.
> 
> I train it with 8 A800, the loss is ok in the log, but after a specific step, the model generate whole black image. if I use torch.autograd.set_detect_anomaly(True) in the “for loop” training，I can detect the nan error.

I test result for adams8bit model 50000 steps,the result is ok, maybe you need more step, I remember vae model must madebyollin, default sdxl1.0 is bad result, using test.py can display the result, have a try

**Comment by trikim** [comment]
> > > > Thanks for sharing the training code of IDM-VTON. Around after 2000 steps training, There‘s a problem of 'nan' by using bitsandbytes.optim.AdamW8bit. But if don't use bitsandbytes.optim.AdamW8bit, the GPUs are out of memory.
> > > > Another question is that the paper saids they use adam with batch_size=6, width=768, height=1024, do you know how they succeed to train and GPU is not out of memory?
> > > 
> > > 
> > > ![default](https://private-user-images.githubusercontent.com/174935326/347848117-f0d4438d-d234-4f52-8bf3-43ba1b7c8e3b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTYyMjcsIm5iZiI6MTcyMDc1NTkyNywicGF0aCI6Ii8xNzQ5MzUzMjYvMzQ3ODQ4MTE3LWYwZDQ0MzhkLWQyMzQtNGY1Mi04YmYzLTQzYmExYjdjOGUzYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMDM0NTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTVkN2JlOTAyYjA1ZmJlZWVkYjQ5ODk1YzdmODJhZDA4NDU5ZGJjMjMzNTBlMTU5OWQwMDQ4ODZlMWVkMDViOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s_4SpMhcItO24BszoSW-D1Iozp-4_hThK6eUsMBf9-8) I try to train it use adamw8bit, It is OK, not find the loss is NaN. I train it on 1 A800 GPU, at least 50G for training. Maybe the author use more gpus.
> > 
> > 
> > I train it with 8 A800, the loss is ok in the log, but after a specific step, the model generate whole black image. if I use torch.autograd.set_detect_anomaly(True) in the “for loop” training，I can detect the nan error.
> 
> I test result for adams8bit model 50000 steps,the result is ok, maybe you need more step, I remember vae model must madebyollin, default sdxl1.0 is bad result, using test.py can display the result, have a try

Thanks a lot.
I found that maybe the bitsandbytes==0.39.0 cause the nan error. when I upgrade bitsandbytes==0.43.1, the nan error disappear.
Could you tell me the version of your bitsandbytes, accelerate and diffusers?
Now mine is bitsandbytes==0.43.1, accelerate==0.32.1, diffusers==0.25.0.

**Comment by luxiaolili** [comment]
bitsandbytes==0.42.0, accelerate==0.25.0, diffusers==0.25.0.  torch==2.3.0+cu121 torchvision==0.18.0+cu121, transformers=4.36.2. torch version > 2.0.0 is ok. You can follow my train and test codes, I test it, it is OK, only small steps like 5000, you can get the swap result not black.

**Comment by luxiaolili** [comment]
> > > > > Thanks for sharing the training code of IDM-VTON. Around after 2000 steps training, There‘s a problem of 'nan' by using bitsandbytes.optim.AdamW8bit. But if don't use bitsandbytes.optim.AdamW8bit, the GPUs are out of memory.
> > > > > Another question is that the paper saids they use adam with batch_size=6, width=768, height=1024, do you know how they succeed to train and GPU is not out of memory?
> > > > 
> > > > 
> > > > ![default](https://private-user-images.githubusercontent.com/174935326/347848117-f0d4438d-d234-4f52-8bf3-43ba1b7c8e3b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTYyMjcsIm5iZiI6MTcyMDc1NTkyNywicGF0aCI6Ii8xNzQ5MzUzMjYvMzQ3ODQ4MTE3LWYwZDQ0MzhkLWQyMzQtNGY1Mi04YmYzLTQzYmExYjdjOGUzYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMDM0NTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTVkN2JlOTAyYjA1ZmJlZWVkYjQ5ODk1YzdmODJhZDA4NDU5ZGJjMjMzNTBlMTU5OWQwMDQ4ODZlMWVkMDViOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s_4SpMhcItO24BszoSW-D1Iozp-4_hThK6eUsMBf9-8) I try to train it use adamw8bit, It is OK, not find the loss is NaN. I train it on 1 A800 GPU, at least 50G for training. Maybe the author use more gpus.
> > > 
> > > 
> > > I train it with 8 A800, the loss is ok in the log, but after a specific step, the model generate whole black image. if I use torch.autograd.set_detect_anomaly(True) in the “for loop” training，I can detect the nan error.
> > 
> > 
> > I test result for adams8bit model 50000 steps,the result is ok, maybe you need more step, I remember vae model must madebyollin, default sdxl1.0 is bad result, using test.py can display the result, have a try
> 
> Thanks a lot. I found that maybe the bitsandbytes==0.39.0 cause the nan error. when I upgrade bitsandbytes==0.43.1, the nan error disappear. Could you tell me the version of your bitsandbytes, accelerate and diffusers? Now mine is bitsandbytes==0.43.1, accelerate==0.32.1, diffusers==0.25.0.


bitsandbytes==0.42.0, accelerate==0.25.0, diffusers==0.25.0. torch==2.3.0+cu121 torchvision==0.18.0+cu121, transformers=4.36.2. torch version > 2.0.0 is ok. You can follow my train and test codes, I test it, it is OK, only small steps like 5000, you can get the swap result not black.
