### ISSUE TITLE
请教一下训练需要的显存大小

### ISSUE THREAD

**Issue by huang997733** [luxiaolili/IDM-VTON-train#10]
你好

我目前在使用8张L4 一个L4有24gb的显存 在跑训练的时候会爆显存
我看到idm那边是用 四张A800 每个是40gb
您这边是一张A100
8张L4的总显存肯定是够的 所以想问问 是不是单张卡的显存也有讲究

谢谢

**Comment by luxiaolili** [comment]
> 你好
> 
> 我目前在使用8张L4 一个L4有24gb的显存 在跑训练的时候会爆显存 我看到idm那边是用 四张A800 每个是40gb 您这边是一张A100 8张L4的总显存肯定是够的 所以想问问 是不是单张卡的显存也有讲究
> 
> 谢谢

单张卡也有要求的训练unet至少要40G，而且40G 要开8bit adam, 我是单张80G卡训练的

**Comment by huang997733** [comment]
> > 你好
> > 我目前在使用8张L4 一个L4有24gb的显存 在跑训练的时候会爆显存 我看到idm那边是用 四张A800 每个是40gb 您这边是一张A100 8张L4的总显存肯定是够的 所以想问问 是不是单张卡的显存也有讲究
> > 谢谢
> 
> 单张卡也有要求的训练unet至少要40G，而且40G 要开8bit adam, 我是单张80G卡训练的

好的好的 感谢回复！
