### ISSUE TITLE
fail to load model

### ISSUE THREAD

**Issue by Nomination-NRB** [luxiaolili/IDM-VTON-train#4]
```python
# line 248
pretrain = os.path.join(args.pretrained_model_name_or_path, 'unet')
load_model_with_zeroed_mismatched_keys(unet, os.path.join(pretrain, 'diffusion_pytorch_model.safetensors'))
```
The diffusion_pytorch_model.safetensors file does not exist in the unet folder, only in the unet_encoder folder, do I need to change it to this:
```python
pretrain = os.path.join(args.pretrained_model_name_or_path, 'unet_encoder')
load_model_with_zeroed_mismatched_keys(unet, os.path.join(pretrain, 'diffusion_pytorch_model.safetensors'))
```

**Comment by luxiaolili** [comment]
> ```python
> # line 248
> pretrain = os.path.join(args.pretrained_model_name_or_path, 'unet')
> load_model_with_zeroed_mismatched_keys(unet, os.path.join(pretrain, 'diffusion_pytorch_model.safetensors'))
> ```
> 
> The diffusion_pytorch_model.safetensors file does not exist in the unet folder, only in the unet_encoder folder, do I need to change it to this:
> 
> ```python
> pretrain = os.path.join(args.pretrained_model_name_or_path, 'unet_encoder')
> load_model_with_zeroed_mismatched_keys(unet, os.path.join(pretrain, 'diffusion_pytorch_model.safetensors'))
> ```
sorry, I fix it,  pretrain = os.path.join(args.inpainting_model_path, 'unet')

**Comment by Nomination-NRB** [comment]
> > ```python
> > # line 248
> > pretrain = os.path.join(args.pretrained_model_name_or_path, 'unet')
> > load_model_with_zeroed_mismatched_keys(unet, os.path.join(pretrain, 'diffusion_pytorch_model.safetensors'))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The diffusion_pytorch_model.safetensors file does not exist in the unet folder, only in the unet_encoder folder, do I need to change it to this:
> > ```python
> > pretrain = os.path.join(args.pretrained_model_name_or_path, 'unet_encoder')
> > load_model_with_zeroed_mismatched_keys(unet, os.path.join(pretrain, 'diffusion_pytorch_model.safetensors'))
> > ```
> 
> sorry, I fix it, pretrain = os.path.join(args.inpainting_model_path, 'unet')

thanks
