### ISSUE TITLE
File "/hy-tmp/caizh/IDM-VTON-train/train.py", line 544, in <module>     main()   File "/hy-tmp/caizh/IDM-VTON-train/train.py", line 457, in main     mask_image_latents = mask_image_latents.to(accelerator.device, dtype=weight_dtype) UnboundLocalError: local variable 'mask_image_latents' referenced before assignment

### ISSUE THREAD

**Issue by all1new** [luxiaolili/IDM-VTON-train#8]
File "/hy-tmp/caizh/IDM-VTON-train/train.py", line 544, in <module>
    main()
  File "/hy-tmp/caizh/IDM-VTON-train/train.py", line 457, in main
    mask_image_latents = mask_image_latents.to(accelerator.device, dtype=weight_dtype)
UnboundLocalError: local variable 'mask_image_latents' referenced before assignment

你好, 这个地方要怎么修改呀

**Comment by luxiaolili** [comment]
> File "/hy-tmp/caizh/IDM-VTON-train/train.py", line 544, in main() File "/hy-tmp/caizh/IDM-VTON-train/train.py", line 457, in main mask_image_latents = mask_image_latents.to(accelerator.device, dtype=weight_dtype) UnboundLocalError: local variable 'mask_image_latents' referenced before assignment
> 
> 你好, 这个地方要怎么修改呀
fix,
 mask_image_latents = compute_vae_encodings(sample['agno'],vae)
